spring.application.name=backend

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost/~/backend
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# JWT (JSON Web Token) ??
jwt.secret=M3Lw0K1d2T5q9X2c7F0v4U8b1Y6r3Z9x5P7o2I4h6J1k9L3m7N8q0R5s6T1u2V4w7X0y1Z3a5B6c9D0e8F4g1H7i9J2k3L5m8N9o1P6q0R4s7T2u5V8w0X3y6Z1a4B7c9D0e
jwt.access-token-expiration-time=86400000


logging.level.org.springframework.security=DEBUG
