spring.application.name=backend

spring.devtools.restart.enabled=false

spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.url=jdbc:h2:tcp://localhost/~/backend;TIME ZONE='UTC'
spring.datasource.url=jdbc:h2:~/grwmdb;
spring.datasource.username=sa
spring.datasource.password=

spring.jackson.serialization.write-dates-as-timestamps=false

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# JWT (JSON Web Token)
jwt.secret=M3Lw0K1d2T5q9X2c7F0v4U8b1Y6r3Z9x5P7o2I4h6J1k9L3m7N8q0R5s6T1u2V4w7X0y1Z3a5B6c9D0e8F4g1H7i9J2k3L5m8N9o1P6q0R4s7T2u5V8w0X3y6Z1a4B7c9D0e
jwt.access-token-expiration-time=8640000


file.upload.dir=${user.home}/project-files
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# firebase key
firebase.service-account.path=${user.home}/service-keys/grwm-541aa-firebase-adminsdk-fbsvc-2ae83c89a5.json


logging.level.org.springframework.security=DEBUG

# Spring Security OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.scope=profile,email,openid


# Spring Security OAuth2 Provider Configuration
# user-name-attribute ??? ??? ??? primary key? name?? ?????.
spring.security.oauth2.client.provider.google.user-name-attribute=name
